# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfctl < Formula
  desc "CLI to query Terraform/OpenTofu state across backends"
  homepage "https://github.com/staranto/tfctlgo"
  version "0.11.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/staranto/homebrew-tfctlgo/releases/download/0.11.1/tfctlgo_0.11.1_darwin_x86_64.tar.gz"
      sha256 "ebf53b7d62023c311e565f0099f5f0fd9e3f14248deec73a82c811973da68294"

      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
        man7.install Dir["docs/man/share/man7/*"] if File.directory?("docs/man/share/man7")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/staranto/homebrew-tfctlgo/releases/download/0.11.1/tfctlgo_0.11.1_darwin_arm64.tar.gz"
      sha256 "68df256b10928a80ca634048eba24f85c1c420e671ac97503f722f6580ef0b6a"

      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
        man7.install Dir["docs/man/share/man7/*"] if File.directory?("docs/man/share/man7")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/staranto/homebrew-tfctlgo/releases/download/0.11.1/tfctlgo_0.11.1_linux_x86_64.tar.gz"
      sha256 "10e1ae605fa1b333c4dd49ee26b6b6ae730afc8ae2d179eba9165ff3889fd414"
      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
        man7.install Dir["docs/man/share/man7/*"] if File.directory?("docs/man/share/man7")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/staranto/homebrew-tfctlgo/releases/download/0.11.1/tfctlgo_0.11.1_linux_arm64.tar.gz"
      sha256 "d773ff17a9374beb052af98351f22a4638038665a48d045af0aa8cbe9c5c0ea6"
      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
        man7.install Dir["docs/man/share/man7/*"] if File.directory?("docs/man/share/man7")
      end
    end
  end

  test do
    system "#{bin}/tfctl", "--version"
  end
end
