# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tfctl < Formula
  desc "CLI to query Terraform/OpenTofu state across backends"
  homepage "https://github.com/staranto/tfctl"
  version "0.6.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/staranto/tfctlgo/releases/download/0.6.6/tfctlgo_0.6.6_darwin_x86_64.tar.gz"
      sha256 "4ba7cf55cc482ac832e8bcc779ec6d846fde5134ecf29bd21db21cbe3abe6be3"

      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
        man7.install Dir["docs/man/share/man7/*"] if File.directory?("docs/man/share/man7")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/staranto/tfctlgo/releases/download/0.6.6/tfctlgo_0.6.6_darwin_arm64.tar.gz"
      sha256 "dcb81fc361ce6219e632ceda052c1d80029ff726f19f4c587c0013879eb8bc51"

      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
        man7.install Dir["docs/man/share/man7/*"] if File.directory?("docs/man/share/man7")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/staranto/tfctlgo/releases/download/0.6.6/tfctlgo_0.6.6_linux_x86_64.tar.gz"
      sha256 "c643392deaec5aecf4c73b93a93b9628de1ce0bf8d74aef36c15b96e75d1927d"
      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
        man7.install Dir["docs/man/share/man7/*"] if File.directory?("docs/man/share/man7")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/staranto/tfctlgo/releases/download/0.6.6/tfctlgo_0.6.6_linux_arm64.tar.gz"
      sha256 "2870742524937da8f670d570cd7966f326b74a2d2e2167b35f1c53309a61faac"
      def install
        bin.install "tfctl"
        man1.install Dir["docs/man/share/man1/*"] if File.directory?("docs/man/share/man1")
        man7.install Dir["docs/man/share/man7/*"] if File.directory?("docs/man/share/man7")
      end
    end
  end

  test do
    system "#{bin}/tfctl", "--version"
  end
end
